// src/components/vue/SignupForm.vue
<script setup lang="ts">
import FormWizard from '@/components/vue/FormWizard.vue';
import { submitSignup } from '@/lib/api';
import { signupForm } from '@/lib/forms/signup-form';

const props = defineProps<{ next: string }>();

function goToOnboarding() {
  window.location.href = props.next;
}
</script>

<template>
  <FormWizard
    :config="signupForm"
    :submit="submitSignup"
    submit-label="Create account"
    submitting-label="Creating your account…"
    success-title="Account created"
    success-description="Taking you to setup…"
    :on-success="goToOnboarding"
  />
</template>

// src/components/svelte/SignupForm.svelte
<script lang="ts">
import FormWizard from '@/components/svelte/FormWizard.svelte';
import { submitSignup } from '@/lib/api';
import { signupForm } from '@/lib/forms/signup-form';

let { next }: { next: string } = $props();
</script>

<FormWizard
  config={signupForm}
  submit={submitSignup}
  submitLabel="Create account"
  submittingLabel="Creating your account…"
  successTitle="Account created"
  successDescription="Taking you to setup…"
  onSuccess={() => {
    window.location.href = next;
  }}
/>
